username: admin
password: password
orders:
  - destination: cluster1
    charts:
      - repository: https://github.com/rbxorkt12/cicdexample.git
        path: chart1
        revision: chart1_branch
      - repository: https://github.com/rbxorkt12/cicdexample.git
        path: chart2
        revision: chart2_branch

  - destination: cluster2
    charts:
      - repository: https://github.com/rbxorkt12/cicdexample.git
        path: chart1
        revision: chart1_branch
      - repository: https://github.com/rbxorkt12/cicdexample.git
        path: chart3
        revision: chart3_branch
