apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: appcd-template-
spec:
  podGC:
    strategy: OnWorkflowSuccess
  volumeClaimTemplates:
    - metadata:
        name: temp-git
      spec:
        storageClassName: "rbd"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi

  entrypoint: appcd
  templates:
    - name: appcd
      steps:
      - - name: repoinfoget
          template: repoinfoget
        - name: argocdinformget
          template: argocdinformget
      - - name: gitdownload
          template: gitdownload
      - - name: lint
          template: lint
      - - name: clusterappget
          template: clusterappget
        - name: configappget
          template: configappget
      - - name: diffconfigncluster
          template: diffconfigncluster



    - name: argocdinformget

    - name: gitdownload
      inputs:
        artifacts:
          - name: temporary-git
            path: /github/argogyu
            git:
              repo: {{input.어쩌구저쩌}}
      container:
        image: alpine:3.8
        command: [sh, -c]
        args: ["
          ls -al /github/argogyu;
          cp -r /github/argogyu /tmp;
          ls -al /tmp;
        "]
        volumeMounts:
          - name: temp-git
            mountPath: /tmp

    - name: lint
      container:
        image: rbxorkt12/lint
        command: [sh, -c]
        args: ["
          ./lint < /tmp/Autoconfig
          ./lint < /tmp/Manualconfig
        "]
        volumeMounts:
          - name: temp-git
            mountPath: /tmp

    - name:

    -

