
orders:
  - destination: https://kubernetes.default.svc
    charts:
      - repository: https://github.com/helm/charts.git
        revision: master
        subpaths:
          - path: stable/chaoskube
            name: abc
            namespace: default
            chartvalue: values.yaml
            chartdeploystrategy: Canary
